version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
clone_depth: 5
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
install:
- ps: >-
    if($($env:APPVEYOR))

    {

    $firstCommit = $(git log --pretty=format:'%H' -n -1).Length;

    $firstCommitHash = $(git log --pretty=format:'%H' -n -1)[$firstCommit-1];

    Write-Host "First Commit Hash:" $firstCommitHash;

    $firstCommitDate = (git show -s --format=%ci $firstCommitHash);

    Write-Host "First Commit Date:" $firstCommitDate;

    [datetime]$FCDateTime = $firstCommitDate;

    #Write-Host $FCDateTime

    $FCyear = $FCDateTime.ToString("y.").TrimEnd('.');

    #Write-Host $FCyear

    $timeZone0 = [TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Turkey Standard Time");

    $timeZone = $timeZone0;

    Write-Host "Current System Time:" $timeZone;

    [datetime]$DateTime = $timeZone;

    $year = $DateTime.ToString("y.").TrimEnd('.');

    $month = $DateTime.ToString("M.").TrimEnd('.');

    $day = $DateTime.ToString("d.").TrimEnd('.');

    $hourMinute = $DateTime.ToString(".HHmm").TrimStart('.').TrimStart('0');

    $buildYear = (($year - $FCyear) + 1);

    #$buildTime = $DateTime.ToString("M.d.hmm");

    $newBuildNumber = "$buildYear.$month.$day.$hourMinute";

    Write-Host "New Nuget Package Version:" $newBuildNumber

    Update-AppveyorBuild -Version $newBuildNumber;

    }

    else

    {
        Write-Host "AppVeyor was not detected";
    }
build_script:
- ps: >-
    if($($env:APPVEYOR))
    {

    $SVersion = $($env:APPVEYOR_BUILD_VERSION);
    Write-Host "$($env:APPVEYOR_PROJECT_NAME) Version:$SVersion";

   nuget restore WindowsForm.Console.sln;
    $msbuild = \"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\amd64\\MSBuild.exe\"
    & $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.5 /p:OutputPath=\"bin\\v4.5\";
& $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath=\"bin\\v4.5.1\";
& $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.5.2 /p:OutputPath=\"bin\\v4.5.2\";
& $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.6 /p:OutputPath=\"bin\\v4.6\";
& $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.6.1 /p:OutputPath=\"bin\\v4.6.1\";
& $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.6.2 /p:OutputPath=\"bin\\v4.6.2\";
#& $msbuild WindowsForm.Console.sln /property:Configuration=Release /p:TargetFrameworkVersion=v4.7 /p:OutputPath=\"bin\\v4.7\";

nuget pack WindowsForm.Console.nuspec -version $SVersion;

    Push-AppveyorArtifact \"$($env:APPVEYOR_BUILD_FOLDER)\\WindowsForm.Console.$SVersion.nupkg\" -FileName \"WindowsForm.Console.$SVersion.nupkg\" -DeploymentName \"NugetPackage1\";
    }
    else
    {
    Write-Host "AppVeyor was not detected";
    }
test: off
hosts:
  api.nuget.org: 93.184.221.200
skip_commits:
  files:
    - '**/*.md'
